ADD_SCENE(meshimi, start, Start)
ADD_SCENE(meshimi, connect, Connect)
ADD_SCENE(meshimi, test, Test)
ADD_SCENE(meshimi, configuration, Configuration)
ADD_SCENE(meshimi, about, About)
ADD_SCENE(meshimi, mode, Mode)
